### ISSUE TITLE
Missing "main" python file that imports the library and generates a movement

### ISSUE THREAD

**Issue by olsonk** [olsonk/pyRosita#1]
Need to include an `example.py` file that demonstrates usage of the library.

**Comment by olsonk** [comment]
Added this file in [commit 4cf9e1c1199e7568cb52929d56c0eeddf0ec47a8](https://github.com/olsonk/pyRosita/commit/7d6ed4ab2210d29f27b773440f4400a1f11bedfc)

**Comment by jteller** [comment]
Nice -- I even got an email for this, which really helps.

Maybe we should do code comments using this (so at least it's in-tool as opposed to emails).
