### ISSUE TITLE
Add descriptive comment headers to each class

### ISSUE THREAD

**Issue by olsonk** [olsonk/pyRosita#2]
Each class has a small comment header describing its attributes. This section needs to be fleshed out with descriptions of each class method, along with how they are used.

**Comment by olsonk** [comment]
Please see [this commit](https://github.com/olsonk/pyRosita/commit/bb8c34fa0c78fb97ffb73e2b9edf7eef88c2856e). This follows Python Docstring style guide and general commenting conventions to provide documentation. Should I continue with this format?

**Comment by jteller** [comment]
Yes -- that format looks great!

**Comment by olsonk** [comment]
Completed documenting rt_hardware and sequencer files. Documented all classes and class methods.

See [this commit](https://github.com/olsonk/pyRosita/commit/91d579b0b2d35558f53b0727a914742523db9f1b) for rt_hardware docs.
See [this commit](https://github.com/olsonk/pyRosita/commit/7dbda175da1c3db8a6cb205608258f5fe969e8ab) for sequencer docs.
